package processor

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/IceWreck/VoxStrip/pkg/store"
	"go.senan.xyz/taglib"
)

// taglibMetadataExtractor implements MetadataExtractor using go-taglib
type taglibMetadataExtractor struct{}

// newTaglibMetadataExtractor creates a new taglib-based metadata extractor
func newTaglibMetadataExtractor() *taglibMetadataExtractor {
	return &taglibMetadataExtractor{}
}

// extractMetadata extracts metadata and cover art from an audio file using taglib
func (e *taglibMetadataExtractor) extractMetadata(ctx context.Context, audioPath string) (*store.Metadata, int64, []byte, error) {
	slog.Debug("extracting metadata", "file", audioPath)

	// Read tags
	tags, err := taglib.ReadTags(audioPath)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("failed to read audio tags: %w", err)
	}

	// Read properties (including duration)
	props, err := taglib.ReadProperties(audioPath)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("failed to read audio properties: %w", err)
	}

	// Try to extract cover art
	var coverArt []byte
	coverArt, err = taglib.ReadImage(audioPath)
	if err != nil {
		// Log debug but don't fail - cover art is optional
		slog.Debug("no cover art found", "file", audioPath, "error", err)
		coverArt = nil
	}

	// Helper function to get first value from tag map
	getFirst := func(key string) string {
		if values, exists := tags[key]; exists && len(values) > 0 {
			return values[0]
		}
		return ""
	}

	metadata := &store.Metadata{
		Title:       getFirst("TITLE"),
		Artist:      getFirst("ARTIST"),
		Album:       getFirst("ALBUM"),
		AlbumArtist: getFirst("ALBUMARTIST"),
		Genre:       getFirst("GENRE"),
		Lyrics:      getFirst("LYRICS"),
	}

	// props.Length is a time.Duration (nanoseconds), not seconds
	duration := props.Length.Milliseconds()

	slog.Debug("metadata extracted",
		"title", metadata.Title,
		"artist", metadata.Artist,
		"album", metadata.Album,
		"duration_ms", duration,
		"has_cover_art", len(coverArt) > 0,
	)

	return metadata, duration, coverArt, nil
}

// writeMetadata writes metadata and cover art to an audio file
func (e *taglibMetadataExtractor) writeMetadata(ctx context.Context, audioPath string, metadata *store.Metadata, coverArt []byte, stemType string) error {
	slog.Debug("writing metadata", "file", audioPath, "stem", stemType)

	// Build tags map
	tags := make(map[string][]string)

	// Add basic metadata if available
	if metadata.Title != "" {
		title := metadata.Title
		if stemType != "" {
			title = fmt.Sprintf("%s (%s)", metadata.Title, stemType)
		}
		tags["TITLE"] = []string{title}
	}
	if metadata.Artist != "" {
		tags["ARTIST"] = []string{metadata.Artist}
	}
	if metadata.Album != "" {
		tags["ALBUM"] = []string{metadata.Album}
	}
	if metadata.AlbumArtist != "" {
		tags["ALBUMARTIST"] = []string{metadata.AlbumArtist}
	}
	if metadata.Genre != "" {
		tags["GENRE"] = []string{metadata.Genre}
	}
	if metadata.Lyrics != "" {
		tags["LYRICS"] = []string{metadata.Lyrics}
	}

	// Add stem-specific comments
	if stemType != "" {
		comment := fmt.Sprintf("Generated by VoxStrip - %s stem", strings.Title(stemType))
		tags["COMMENT"] = []string{comment}
	}

	// Write tags
	if err := taglib.WriteTags(audioPath, tags, taglib.Clear); err != nil {
		return fmt.Errorf("failed to write audio tags: %w", err)
	}

	// Write cover art if available
	if len(coverArt) > 0 {
		if err := taglib.WriteImage(audioPath, coverArt); err != nil {
			// Log warning but don't fail - cover art is optional
			slog.Warn("failed to write cover art", "file", audioPath, "error", err)
		} else {
			slog.Debug("cover art written", "file", audioPath, "size", len(coverArt))
		}
	}

	slog.Debug("metadata written successfully", "file", audioPath, "stem", stemType)
	return nil
}
